## Ejercicio 1

* Crear un array Numpy con números enteros
* Crear un array Numpy con números flotantes


In [1]:
import numpy as np

ent = np.array([1,2,5,7,8,11,24,26,120])
flt = np.array([0.3,0.9,1.2,4.4,5.6,7.8,10.1])

print(ent)
print(flt)

[  1   2   5   7   8  11  24  26 120]
[ 0.3  0.9  1.2  4.4  5.6  7.8 10.1]


## Ejercicio 2

Dado el siguiente arreglo:
* array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

Se pide:
* Obtener el tercer elemento
* Seleccionar los elementos del array con valores impares

In [2]:
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

ele_3 = array[2]
ele_imp = array[(array % 2 != 0)]

print(ele_3)
print(ele_imp)

3
[1 3 5 7 9]


## Ejercicio 3

Para un conjunto determinado de notas (Leer de consola) implementar un algoritmo para determinar el máximo, min y prom, luego de registrar las nota.

In [6]:
import numpy as np
#Objetivo: Max, min, prom?

cantNotas = int(input('Ingrese cantidad de notas: '))

#Leer notas, Guardelo en un arreglo
arrNotas = np.zeros(cantNotas)
#array([0,0,0,0])

for i in range(cantNotas):
  nota = float(input('Ingrese nota: '))
  arrNotas[i] = nota

#Mostrar resultados
maxNota = np.max(arrNotas)
minNota = np.min(arrNotas)
prom = np.mean(arrNotas)

print('Cantidad de notas:', cantNotas)
print("Máximo: ", maxNota)
print('Minima: ', minNota)
print('Promedio: ', round(prom, 2))

Cantidad de notas: 3
Máximo:  5.0
Minima:  3.0
Promedio:  4.33
